print("ishans first code")
birth_year = input("enter your birth year")
age = 2024 - int(birth_year)
place = input('where is your place')
name = input('what is your name ')
print('hello ' + name)
print('thank you for telling your place ' + place)
print("your age =")
print(age)
print('thank you ' + name)
