# mylist = [1, 2, 3, 6, 1, 3]
# my_tuple = (1, 2, 3, 3, 4, 8, 1)
# mylist.sort()
# print(mylist, 'sort')
# mylist.reverse()
# print(mylist, 'reverse')
# mylist.insert(7, 10)
# mylist.append(56)
# print(mylist.count(3))
# print(mylist.index(2))
# print(my_tuple.count(3))
# print(my_tuple.index(3))
# print(tuple1[1:4])
# print(sorted(tuple1))
# print(tuple1.index(1))
# print(tuple1.count(1))
# print(tuple1.index(1,1))
# print(sorted(tuple1, reverse=True))
# new = tuple(new) conversion to list to tuple
# print(mylist)